In [11]:
import numpy as np

def sor(A, b, x0 = np.copy(b), w=1.8, tol=1e-8, max_iter=1000):
    """
    SOR迭代法求解线性方程组Ax=b
    
    Parameters:
        A: ndarray, 输入的系数矩阵
        b: ndarray, 输入的右端向量
        x0: ndarray, 迭代初始值
        w: float, 松弛因子，默认为1.2
        tol: float, 收敛精度，默认为1e-8
        max_iter: int, 最大迭代次数，默认为1000
    
    Returns:
        x: ndarray, 线性方程组的近似解
    """
    n = len(b)
    x = np.copy(x0)
    for k in range(max_iter):
        for i in range(n):
            x_new = (1 - w) * x[i] + w * (b[i] - np.dot(A[i,:i], x[:i]) - np.dot(A[i,i+1:], x[i+1:])) / A[i,i]
            x[i] = x_new
        if np.linalg.norm(A @ x - b) < tol:
            break
    return x

def jacobi(A, b, x0 = np.copy(b), tol=1e-8, max_iter=1000):
    """
    Jacobi迭代法求解线性方程组Ax=b
    
    Parameters:
        A: ndarray, 输入的系数矩阵
        b: ndarray, 输入的右端向量
        x0: ndarray, 迭代初始值
        tol: float, 收敛精度，默认为1e-8
        max_iter: int, 最大迭代次数，默认为1000
    
    Returns:
        x: ndarray, 线性方程组的近似解
    """
    n = len(b)
    x = np.copy(x0)
    for k in range(max_iter):
        x_new = np.zeros_like(x)
        for i in range(n):
            x_new[i] = (b[i] - np.dot(A[i,:i], x[:i]) - np.dot(A[i,i+1:], x[i+1:])) / A[i,i]
        if np.linalg.norm(x_new - x) < tol:
            break
        x = np.copy(x_new)
    return x


def gauss_seidel(A, b, x0 = np.copy(b), tol=1e-8, max_iter=1000):
    """
    Gauss-Seidel迭代法求解线性方程组Ax=b
    
    Parameters:
        A: ndarray, 输入的系数矩阵
        b: ndarray, 输入的右端向量
        x0: ndarray, 迭代初始值
        tol: float, 收敛精度，默认为1e-8
        max_iter: int, 最大迭代次数，默认为1000
    
    Returns:
        x: ndarray, 线性方程组的近似解
    """
    n = len(b)
    x = np.copy(x0)
    for k in range(max_iter):
        for i in range(n):
            x[i] = (b[i] - np.dot(A[i,:i], x[:i]) - np.dot(A[i,i+1:], x[i+1:])) / A[i,i]
        if np.linalg.norm(A @ x - b) < tol:
            break
    return x

A = np.array([[4, 3, 0],
              [3, 4, -1],
              [0, -1, 4]])
b = np.array([24, 30, -24])
x0 = np.array([0, 0, 0])

X = jacobi(A=A, b=b)
print(X)
X = gauss_seidel(A, b, x0)
print(X)
X = sor(A, b, x0)
print(X)

[ 3  5 -5]
[ 3  4 -5]
[ 3  4 -5]
